server:
  port: 8082
spring:
  application:
    name: SERVICE-CAR
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
      jdbc:mysql://localhost:3306/carservicedb
    username: "root1"
    password: "pass123"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false